version: "2"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=admin
    ports:
      - "8082:3306"
  website:
    container_name: php72
    image: phpdev
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql
